snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: {{ env_var("ACCOUNT") }}

      # User/password auth
      user: {{ env_var("USER") }}
      password: {{ env_var("PASSWORD") }}

      role: {{ env_var("ROLE") }}
      database: {{ env_var("DATABASE") }}
      warehouse: {{ env_var("WAREHOUSE") }}
      schema: {{ env_var("SCHEMA") }}
      threads: 4
      client_session_keep_alive: False
      #query_tag: [anything]

      # optional
      # connect_retries: 0 # default 0
      # connect_timeout: 10 # default: 10
      # retry_on_database_errors: False # default: false
      # retry_all: False  # default: false
      # reuse_connections: False # default: false